### ISSUE TITLE
ReferenceError: Invalid left-hand side in assignment in pad/lib/index.js:13

### ISSUE THREAD

**Issue by DeemoHarlos** [adaltas/node-pad#11]
```
deemo@deemo-UX410UQK:~/projects/test$ node server.js 
/home/deemo/projects/test/node_modules/pad/lib/index.js:13
    [length, text] = [text, length];
    ^

ReferenceError: Invalid left-hand side in assignment
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:374:25)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/home/deemo/projects/test/server.js:1:63)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)
```

How to duplicate:
```
mkdir test
cd test
npm install pad
vim server.js # type `require("pad")` and save
node server.js
```

I got this error when I wanted to use this in my node.js project.
I have updated npm to the latest version. Can anybody tell me what I am doing wrong?

**Comment by wdavidw** [comment]
Which Node.js version are u using, probably 7 or below

**Comment by DeemoHarlos** [comment]
Ahh, I found out that the npm and node in Ubuntu package is not updated :(
Just upgraded from the official website.

**Comment by jrista** [comment]
I am actually having this problem as well. In my case, I am trying to run an Ionic project on older versions of Android. I believe my issue is due to the fact that the browsers on Android older than 7.0 do not have native support for ES6. Is there any chance this library could be transpiled from coffeescript with an older ES target version? Perhaps even ES3? That would make it a far more compatible library on the browser side...

**Comment by wdavidw** [comment]
I just publish [version 2.2.1](https://www.npmjs.com/package/pad)

**Comment by jrista** [comment]
@wdavidw Thanks. Appreciate it!
